version: "3"
services:
  api:
    build: .\api
    container_name: api-container
    ports:
      - 3333:3000
  web:
    build: .\web
    container_name: web-container
    volumes:
      - ./web:/usr/local/apache2/htdocs/
    ports:
      - 81:80
    depends_on:
      - api